# Apple WeatherKit to openweathermap icon code translator
#   WeatherCondition, description, openweathermap icon code, matrix icon index

kit_to_map_icon = {
    "BlowingDust": ["Blowing dust or sand.", "50", 8],
    "Clear": ["Clear.", "01", 0],
    "Cloudy": ["Cloudy, overcast.", "04", 3],
    "Foggy": ["Fog.", "50", 8],
    "Haze": ["Haze.", "50", 8],
    "MostlyClear": ["Mostly clear.", "02", 1],
    "MostlyCloudy": ["Mostly cloudy.", "03", 2],
    "PartlyCloudy": ["Partly cloudy.", "02", 1],
    "Smoky": ["Smoky.", "50", 8],
    "Breezy": ["Breezy, light wind.", "50", 8],
    "Windy": ["Windy.", "50", 8],
    "Drizzle": ["Drizzle or light rain.", "10", 5],
    "HeavyRain": ["Heavy rain.", "09", 4],
    "IsolatedThunderstorms": ["Light thunderstorms.", "11", 6],
    "Rain": ["Rain.", "09", 4],
    "SunShowers": ["Rain with visible sun.", "10", 5],
    "ScatteredThunderstorms": ["Scattered thunderstorms.", "11", 6],
    "StrongStorms": ["Strong thunderstorms.", "11", 6],
    "Thunderstorms": ["Thunderstorms.", "11", 6],
    "Frigid": ["Frigid conditions.", "50", 8],
    "Hail": ["Hail.", "13", 7],
    "Hot": ["High temperatures.", "01", 0],
    "Flurries": ["Flurries or light snow.", "13", 7],
    "Sleet": ["Sleet.", "13", 7],
    "Snow": ["Snow.", "13", 7],
    "SunFlurries": ["Snow flurries with visible sun.", "13", 7],
    "WintryMix": ["Wintry mix.", "13", 7],
    "Blizzard": ["Blizzard.", "13", 7],
    "BlowingSnow": ["Blowing or drifting snow.", "13", 7],
    "FreezingDrizzle": ["Freezing drizzle or light rain.", "09", 4],
    "FreezingRain": ["Freezing rain.", "09", 4],
    "HeavySnow": ["Heavy snow.", "13", 7],
    "Hurricane": ["Hurricane.", "50", 8],
    "TropicalStorm": ["Tropical storm.", "50", 8],
}
